version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env/dev.env
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env/dev.env
    ports:
      - 5432:5432

volumes:
  pg_data: